<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BookRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

/**
 * A physical or digital book tracked by the library.
 *
 * The entity is intentionally minimal: only the fields described in the
 * acceptance criteria. Identifiers are generated by the database and the
 * field types match what callers will actually send over the wire.
 */
#[ORM\Entity(repositoryClass: BookRepository::class)]
#[ORM\Table(name: 'books')]
#[ORM\HasLifecycleCallbacks]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private string $title;

    #[ORM\Column(type: 'string', length: 255)]
    private string $publisher;

    #[ORM\Column(type: 'string', length: 255)]
    private string $author;

    #[ORM\Column(type: 'string', length: 100)]
    private string $genre;

    #[ORM\Column(type: 'date_immutable')]
    private DateTimeImmutable $publicationDate;

    #[ORM\Column(type: 'integer', options: ['unsigned' => true])]
    private int $wordCount;

    /**
     * Price stored as a string-typed decimal to avoid floating-point drift.
     * Doctrine's `decimal` maps to a PHP string by default, and we keep it
     * that way to preserve precision; callers send/receive plain numbers.
     */
    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    private string $priceUsd;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $updatedAt;

    public function __construct(
        string $title,
        string $publisher,
        string $author,
        string $genre,
        DateTimeImmutable $publicationDate,
        int $wordCount,
        string $priceUsd,
    ) {
        $this->title = $title;
        $this->publisher = $publisher;
        $this->author = $author;
        $this->genre = $genre;
        $this->publicationDate = $publicationDate;
        $this->wordCount = $wordCount;
        $this->priceUsd = $priceUsd;

        $now = new DateTimeImmutable();
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublisher(): string
    {
        return $this->publisher;
    }

    public function setPublisher(string $publisher): self
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getAuthor(): string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getGenre(): string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getPublicationDate(): DateTimeImmutable
    {
        return $this->publicationDate;
    }

    public function setPublicationDate(DateTimeImmutable $publicationDate): self
    {
        $this->publicationDate = $publicationDate;

        return $this;
    }

    public function getWordCount(): int
    {
        return $this->wordCount;
    }

    public function setWordCount(int $wordCount): self
    {
        $this->wordCount = $wordCount;

        return $this;
    }

    public function getPriceUsd(): string
    {
        return $this->priceUsd;
    }

    public function setPriceUsd(string $priceUsd): self
    {
        $this->priceUsd = $priceUsd;

        return $this;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): DateTimeImmutable
    {
        return $this->updatedAt;
    }

    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new DateTimeImmutable();
    }
}
